language: node_js
node_js:
  - '0.10'
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH
addons:
  firefox: "34.0"
before_script:
  - npm install -g grunt-cli