branches:
  only:
    - "master"
language: node_js
node_js:
  - '0.10'
env:
  - SLIMERJSLAUNCHER=$(which firefox)
    DISPLAY=:99.0
    PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH
    ENGINE="slimerjs"
    ENGINE_VERSION="0.9.4"
    ENGINE_ARCHIVE_URL="http://download.slimerjs.org/releases/0.9.4/slimerjs-0.9.4-linux-x86_64.tar.bz2"
    ENGINE_EXECUTABLE="engine/slimerjs";
    ENGINE_FLAGS="--local-to-remote-url-access=yes --ignore-ssl-errors=yes"
addons:
  firefox: "34.0"
before_script:
  - echo "Installing $ENGINE $ENGINE_VERSION from $ENGINE_ARCHIVE_URL"
  - wget $ENGINE_ARCHIVE_URL --output-document=engine.tar.bz2
  - mkdir engine && tar --strip-components=1 -xvf engine.tar.bz2 -C engine
  - ls -la $ENGINE_EXECUTABLE && $ENGINE_EXECUTABLE --version;
  - export ENGINE_EXECUTABLE="$ENGINE_EXECUTABLE $ENGINE_FLAGS"
  - echo $SLIMERJSLAUNCHER
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g casperjs
  - npm install -g grunt-cli