language: node_js
node_js:
  - '0.10'
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH
addons:
  firefox: "34.0"
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g casperjs
  - npm install -g slimerjs
  - npm install -g grunt-cli